sudo: required
git:
  depth: 3
  submodules: false
env:
  matrix:
  - OS_TYPE=debian OS_VERSION=8 OS_NAME=jessie
  - OS_TYPE=debian OS_VERSION=9 OS_NAME=stretch
  #- OS_TYPE=centos OS_VERSION=latest OS_NAME=centos7
  - OS_TYPE=ubuntu OS_VERSION=16.04 OS_NAME=xenial
  - OS_TYPE=ubuntu OS_VERSION=18.04 OS_NAME=bionic
services:
- docker
addons:
  apt:
    update: true
before_install:
- sudo apt-get -qq update
- sudo docker pull ${OS_TYPE}:${OS_VERSION}
script:
- docker run -ti -v ${TRAVIS_BUILD_DIR}/..:/work:rw ${OS_TYPE}:${OS_VERSION} /bin/bash -c "cd /work/binutils; ./tests.sh ${OS_TYPE} ${OS_VERSION}"
deploy:
  provider: packagecloud
  on:
    branch: bootstrap
    condition: -n "${PACKAGECLOUD_TOKEN}"
  skip_cleanup: true
  dist: "${OS_TYPE}/${OS_NAME}"
  repository: "main"
  username: "hermitcore"
  token: "${PACKAGECLOUD_TOKEN}"
  package_glob: build/*.deb
  force: true
